on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


name: Check

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['v1.5.0']
        os: [ubuntu-latest, macOS-latest, windows-latest]
      max-parallel: 1


    steps:
      - uses: actions/checkout@v1.0.0

      - name: "Install matplotlib"
        run: pip3 install matplotlib

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: "Install packages"
        run: julia -p 1 src/install_packages.jl
        shell: bash

      - name: "Test"
        run: julia -p 1 src/simulation_example.jl
        shell: bash